"""add RefreshTokenModel

Revision ID: 310e2fb7fb1b
Revises: 3abee5f22bc8
Create Date: 2025-12-31 23:17:52.870297

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "310e2fb7fb1b"
down_revision: Union[str, Sequence[str], None] = "3abee5f22bc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.id"],
            name=op.f("fk__refresh_token__user_id__auth"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__refresh_token")),
    )
    op.create_index(
        op.f("ix__refresh_token__expires_at"),
        "refresh_token",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix__refresh_token__token_hash"),
        "refresh_token",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix__refresh_token__user_id"), "refresh_token", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__refresh_token__user_id"), table_name="refresh_token")
    op.drop_index(op.f("ix__refresh_token__token_hash"), table_name="refresh_token")
    op.drop_index(op.f("ix__refresh_token__expires_at"), table_name="refresh_token")
    op.drop_table("refresh_token")
    # ### end Alembic commands ###
