"""initial models: auth and verification_code

Revision ID: 566a47eca596
Revises: 80e0a166260b
Create Date: 2025-12-30 18:27:41.427558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '566a47eca596'
down_revision: Union[str, Sequence[str], None] = '80e0a166260b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__auth'))
                    )
    op.create_index(op.f('ix__auth__email'), 'auth', ['email'], unique=True)
    op.create_table('verification_code',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('code', sa.String(length=6), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('is_used', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__verification_code'))
                    )
    op.create_index(op.f('ix__verification_code__email'), 'verification_code', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__verification_code__email'), table_name='verification_code')
    op.drop_table('verification_code')
    op.drop_index(op.f('ix__auth__email'), table_name='auth')
    op.drop_table('auth')
    # ### end Alembic commands ###
