"""goals app

Revision ID: bad859eea233
Revises: 310e2fb7fb1b
Create Date: 2026-01-01 17:03:36.007064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bad859eea233"
down_revision: Union[str, Sequence[str], None] = "310e2fb7fb1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("target_value", sa.Integer(), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("current_value", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["goals.id"],
            name=op.f("fk__goals__parent_id__goals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.id"],
            name=op.f("fk__goals__user_id__auth"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__goals")),
    )
    op.create_index(op.f("ix__goals__parent_id"), "goals", ["parent_id"], unique=False)
    op.create_index(op.f("ix__goals__user_id"), "goals", ["user_id"], unique=False)
    op.create_table(
        "progress_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("goal_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("mood", sa.String(length=50), nullable=True),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
            name=op.f("fk__progress_events__goal_id__goals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__progress_events")),
    )
    op.create_index(
        op.f("ix__progress_events__goal_id"),
        "progress_events",
        ["goal_id"],
        unique=False,
    )
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("goal_id", sa.Integer(), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("img_url", sa.String(length=500), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["progress_events.id"],
            name=op.f("fk__images__event_id__progress_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
            name=op.f("fk__images__goal_id__goals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__images")),
    )
    op.create_index(op.f("ix__images__event_id"), "images", ["event_id"], unique=False)
    op.create_index(op.f("ix__images__goal_id"), "images", ["goal_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__images__goal_id"), table_name="images")
    op.drop_index(op.f("ix__images__event_id"), table_name="images")
    op.drop_table("images")
    op.drop_index(op.f("ix__progress_events__goal_id"), table_name="progress_events")
    op.drop_table("progress_events")
    op.drop_index(op.f("ix__goals__user_id"), table_name="goals")
    op.drop_index(op.f("ix__goals__parent_id"), table_name="goals")
    op.drop_table("goals")
    # ### end Alembic commands ###
